version: '3.8'
services:
  app:
    build: .
    container_name: webkontraktor_app
    ports: ["8007:8000"]
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: webkontraktors_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webkontraktor
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports: ["3313:3306"]
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: webkontraktor
    depends_on:
      - db
    ports:
      - "8087:80"
    environment:
      PMA_HOST: db
      PMA_USER: laravel
      PMA_PASSWORD: secret
      UPLOAD_LIMIT: 128M

volumes:
  db_data: